'''
Created by Erick Urquilla, Department of Physics and Astronomy, University of Tennessee, Knoxville.
This script is used to generate an HDF5 file that contains constant background matter information: rho (density), Yₑ (electron fraction), and T (temperature). 
The HDF5 file generated by this script will be used as input for background matter quantities in EMU.
'''

import numpy as np
import h5py
import nsm_grid_generator

# EMU grid parameters
ncellsx = 2 # scalar, number of cells in x-direction
ncellsy = 2 # scalar, number of cells in y-direction
ncellsz = 2 # scalar, number of cells in z-direction
xmin =  0.0 #cm
xmax =  2.0e4 #cm
ymin = 0.0 #cm
ymax = 2.0e4 #cm
zmin = 0.0 #cm
zmax = 2.0e4 #cm

# Create EMU mesh
centers, mesh = nsm_grid_generator.create_grid([ncellsx, ncellsy, ncellsz], [[xmin, xmax], [ymin, ymax], [zmin, zmax]]) # cm

rho_cons = 1802418929.1457505 # g/ccm
T_cons   = 5.0246353 # MeV
Ye_cons  = 0.46005958 # n_electron - n_positron / n_barions

# Create arrays to store the interpolated values of T, rho, and Ye.
rho = np.full( ( ncellsx, ncellsy, ncellsz ), rho_cons ) # array of size (ncellsx, ncellsy, ncellsz)
T   = np.full( ( ncellsx, ncellsy, ncellsz ), T_cons ) # array of size (ncellsx, ncellsy, ncellsz)
Ye  = np.full( ( ncellsx, ncellsy, ncellsz ), Ye_cons ) # array of size (ncellsx, ncellsy, ncellsz)

# Write hdf5 file with all the data
with h5py.File('rho_Ye_T.hdf5', 'w') as hdf:
    hdf.create_dataset("ncellsx", data=ncellsx)
    hdf.create_dataset("ncellsy", data=ncellsy)
    hdf.create_dataset("ncellsz", data=ncellsz)
    hdf.create_dataset("xmin_cm", data=xmin)
    hdf.create_dataset("xmax_cm", data=xmax)
    hdf.create_dataset("ymin_cm", data=ymin)
    hdf.create_dataset("ymax_cm", data=ymax)
    hdf.create_dataset("zmin_cm", data=zmin)
    hdf.create_dataset("zmax_cm", data=zmax)
    hdf.create_dataset("rho_g|ccm", data=rho)
    hdf.create_dataset("T_Mev", data=T)
    hdf.create_dataset("Ye", data=Ye)