'''
Created by Debraj Kundu, Department of Physics and Astronomy, University of Tennessee, Knoxville.
This script is used to generate an HDF5 file that contains the rho, Y_e, T background for the radiating sphere test. 
The HDF5 file generated by this script will be used as input for background matter quantities in EMU.
'''

import numpy as np
import h5py
import nsm_grid_generator

#Here we are using spherical coordinate system. x-> r, y-> theta, z-> phi
# EMU grid parameters

R       = 1.17e6    # sphere radius, cm
ncellsx = 100 # scalar, number of cells in x-direction
ncellsy = 1 # scalar, number of cells in y-direction
ncellsz = 1 # scalar, number of cells in z-direction
xmin    = 0.0 #cm     
xmax    = 2.2e6 #cm
ymin    = 0.0 #radians
ymax    = np.pi #radians
zmin    = 0.0 #radians
zmax    = 2.0*np.pi #radians

# Create EMU mesh
centers, mesh = nsm_grid_generator.create_grid([ncellsx, ncellsy, ncellsz], [[xmin, xmax], [ymin, ymax], [zmin, zmax]]) # cm

#Thermodynamic quantities inside the sphere
rho_in = 9.7197e9 # g/ccm
T_in   = 5.1189 # MeV
Ye_in  = 0.3337 # n_electron - n_positron / n_barions

#Thermodynamic quantities outside the sphere ( will hardcode kappa to zero later)
rho_out = 1310038.17 # g/ccm
T_out   = 0.05666306 # MeV
Ye_out  = 0.0453 # n_electron - n_positron / n_barions

#Create arrays rho, T and Ye to store the thermodynamic quantities.
#Comparing the cell center radial distance of each cell with sphere radius (R).
#For cell centers inside and outside the sphere, appropriate thermodynamic quantities are assigned.
mask = mesh[:, :, :, 0] < R   # shape (ncellsx, ncellsy, ncellsz)
rho  = np.where(mask, rho_in, rho_out)
T    = np.where(mask, T_in,   T_out)
Ye   = np.where(mask, Ye_in,  Ye_out)

# Write hdf5 file with all the data
with h5py.File('rho_Ye_T.hdf5', 'w') as hdf:
    hdf.create_dataset("ncellsx", data=ncellsx)
    hdf.create_dataset("ncellsy", data=ncellsy)
    hdf.create_dataset("ncellsz", data=ncellsz)
    hdf.create_dataset("xmin", data=xmin)
    hdf.create_dataset("xmax", data=xmax)
    hdf.create_dataset("ymin", data=ymin) 
    hdf.create_dataset("ymax", data=ymax)
    hdf.create_dataset("zmin", data=zmin)
    hdf.create_dataset("zmax", data=zmax)
    hdf.create_dataset("rho_g|ccm", data=rho)
    hdf.create_dataset("T_Mev", data=T)
    hdf.create_dataset("Ye", data=Ye)
    hdf.create_dataset("vupx", data=np.full_like(rho, 0.0))
    hdf.create_dataset("vupy", data=np.full_like(rho, 0.0))
    hdf.create_dataset("vupz", data=np.full_like(rho, 0.0))