dist: xenial

language: python

python:
  - "3.7-dev"

before_install:
  - export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s|::|:|g")
  - pip install sympy numpy

addons:
   apt: 
      packages:
      - mpich
      - libmpich-dev
      - g++
      - gfortran
      - libgmp-dev
      - libmpfr-dev
      - pandoc
      - doxygen
      - texlive
      - texlive-latex-extra
      - texlive-lang-cjk
      - latexmk

install:
- git submodule init; git submodule update
- cp makefiles/GNUmakefile_travis Exec/GNUmakefile; cd Exec; make

script:
- cd Exec; mpirun -np 2 ./main3d.gnu.DEBUG.TPROF.MPI.ex ../sample_inputs/inputs_msw_test; python ../Scripts/tests/msw_test.py
- cd Exec; mpirun -np 2 ./main3d.gnu.DEBUG.TPROF.MPI.ex ../sample_inputs/inputs_bipolar_test
- cd Exec; mpirun -np 2 ./main3d.gnu.DEBUG.TPROF.MPI.ex ../sample_inputs/inputs_fast_flavor; python ../Scripts/tests/fast_flavor_test.py
- cd Exec; mpirun -np 2 ./main3d.gnu.DEBUG.TPROF.MPI.ex ../sample_inputs/inputs_fast_flavor_nonzerok; python ../Scripts/tests/fast_flavor_k_test.py
