language: c++

os:
- linux

dist: trusty

python:
- 3.6

notifications:
  email:
    recipients:
      - sricher@ncsu.edu
      - dewillcox@lbl.gov
    on_success: change
    on_failure: always

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
    - gfortran-5
    - mpich2
    - libmpich-dev
    - gsl-bin
    - libgsl0-dev
    - libgsl0ldbl
    - zlib1g-dev
    - python3
    - python3-numpy
    - python3-scipy
    - python3-h5py
    - python3-matplotlib
    - gnuplot
    - bzip2
    env:
    - CC=gcc-5
    - CXX=g++-5
    - F90=gfortran-5
    - OMP_NUM_THREADS=4

install:
- cd Exec; make -j
- echo "blank script"

script:
- echo "blank script"