dist: xenial

language: python

python:
  - "3.7-dev"

before_install:
  - export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s|::|:|g")
  - pip install sympy

addons:
   apt: 
      packages:
      - mpich
      - libmpich-dev
      - g++
      - gfortran
      - libgmp-dev
      - libmpfr-dev
      - pandoc
      - doxygen
      - texlive
      - texlive-latex-extra
      - texlive-lang-cjk
      - latexmk

install:
- git submodule init; git submodule update
- cd Exec; make

script:
- cd Exec; mpirun -np 2 ./main3d.gnu.TPROF.MPI.ex inputs_msw_test; python ../Scripts/tests/msw_test.py