FLAVOR_HOME ?= ../
AMREX_HOME ?= ../../../../..

DEBUG	= FALSE

DIM	= 3

COMP = gnu

TINY_PROFILE  = TRUE
USE_PARTICLES = TRUE

PRECISION     = DOUBLE

USE_MPI       = TRUE
USE_OMP       = FALSE
USE_ACC       = FALSE
USE_CUDA      = FALSE

Bpack   :=
Blocs   := . 

include ../Make.Emu
