name: Clang-format

on:
  pull_request:
    branches: development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        ref: refs/heads/${{ github.head_ref }}

    - name: Run tab exterminator script
      run: |
        cd Scripts/util
        ./tab_exterminator.sh

    - name: Run clang-format
      run: |
        find . -regex '.*\.\(cpp\|h\|H\)' | xargs clang-format -i -style=file

    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add --all
        git diff-index --quiet HEAD || git commit -m "Clang-format has tidied up the code."

    - name: Push changes
      uses: ad-m/github-push-action@master
      if: github.repository_owner == 'AMReX-Astro' 
      with:
        branch: ${{ github.head_ref }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
